### ISSUE TITLE
GFR: Add sort logic to series lists

### ISSUE THREAD

**Issue by clingerman** [usnationalarchives/demos#15]
If possible, add a sort logic to the series listed under a creator. If possible, try sorting by "Inclusive End Date." If not possible, try sorting alphabetically by title or numerically by NAID.

**Comment by DominicBM** [comment]
I have changed the sort to alphabetical by title (can easily change it to NAID if desired, but I figured the title is clearer to the reader). It's not easy to sort by inclusive end date at this time, but maybe in the future when we have better sort functionality.
